version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/zcong1993/badge-service

    steps:
      - checkout
      - run:
          name: get deps
          command: |
            go get -u -v golang.org/x/vgo
            make install
      - run:
          name: test
          command: make test
      - run:
          name: build
          command: make build
